import type { Graph } from "./ir";

export const sampleGraph: Graph = {
  id: "main",
  version: 1,
  entryNodeId: "start",
  contract: { inputs: [], outputs: [] },
  nodes: [
    { id: "start", type: "Start", version: 1, props: {}, pos: { x: 0, y: 0 } },
    { id: "const-flag-name", type: "ConstString", version: 1, props: { value: "flag" }, pos: { x: 240, y: 0 } },
    { id: "const-flag-value", type: "ConstBoolean", version: 1, props: { value: true }, pos: { x: 480, y: 0 } },
    { id: "set-flag", type: "SetVar", version: 1, props: {}, pos: { x: 720, y: 0 } },
    { id: "const-intro", type: "ConstString", version: 1, props: { value: "Welcome to the Blueprint Studio demo." }, pos: { x: 960, y: 0 } },
    { id: "show-intro", type: "ShowText", version: 1, props: { label: "Welcome" }, pos: { x: 0, y: 140 } },
    { id: "const-flag-name-read", type: "ConstString", version: 1, props: { value: "flag" }, pos: { x: 240, y: 140 } },
    { id: "get-flag", type: "GetVar", version: 1, props: {}, pos: { x: 480, y: 140 } },
    { id: "const-flag-true", type: "ConstBoolean", version: 1, props: { value: true }, pos: { x: 720, y: 140 } },
    { id: "equals-flag", type: "Equals", version: 1, props: {}, pos: { x: 960, y: 140 } },
    { id: "if-flag", type: "If", version: 1, props: {}, pos: { x: 0, y: 280 } },
    { id: "const-prompt", type: "ConstString", version: 1, props: { value: "Pick a branch to proceed." }, pos: { x: 240, y: 280 } },
    { id: "wait-choice", type: "WaitForChoice", version: 1, props: { choiceALabel: "Happy path", choiceBLabel: "Error path" }, pos: { x: 480, y: 280 } },
    { id: "const-delay", type: "ConstNumber", version: 1, props: { value: 1200 }, pos: { x: 720, y: 280 } },
    { id: "delay", type: "Delay", version: 1, props: {}, pos: { x: 960, y: 280 } },
    { id: "subgraph", type: "Subgraph", version: 1, props: { subgraphId: "subflow" }, pos: { x: 0, y: 420 } },
    { id: "const-alt", type: "ConstString", version: 1, props: { value: "Alt path reached (if flag is false)." }, pos: { x: 240, y: 420 } },
    { id: "show-alt", type: "ShowText", version: 2, props: { title: "Alt Path" }, pos: { x: 480, y: 420 } },
    { id: "const-denom-name", type: "ConstString", version: 1, props: { value: "denom" }, pos: { x: 720, y: 420 } },
    { id: "const-denom-zero", type: "ConstNumber", version: 1, props: { value: 0 }, pos: { x: 960, y: 420 } },
    { id: "set-denom", type: "SetVar", version: 1, props: {}, pos: { x: 0, y: 560 } },
    { id: "const-denom-name-read", type: "ConstString", version: 1, props: { value: "denom" }, pos: { x: 240, y: 560 } },
    { id: "get-denom", type: "GetVar", version: 1, props: {}, pos: { x: 480, y: 560 } },
    { id: "to-number", type: "ToNumber", version: 1, props: {}, pos: { x: 720, y: 560 } },
    { id: "const-dividend", type: "ConstNumber", version: 1, props: { value: 42 }, pos: { x: 960, y: 560 } },
    { id: "divide", type: "Divide", version: 1, props: {}, pos: { x: 0, y: 700 } },
    { id: "const-error", type: "ConstString", version: 1, props: { value: "Error handled via onError path." }, pos: { x: 240, y: 700 } },
    { id: "show-error", type: "ShowText", version: 2, props: { title: "Error" }, pos: { x: 480, y: 700 } },
    { id: "end", type: "End", version: 1, props: {}, pos: { x: 720, y: 700 } },
    { id: "end-alt", type: "End", version: 1, props: {}, pos: { x: 720, y: 460 } },
    { id: "end-error", type: "End", version: 1, props: {}, pos: { x: 720, y: 760 } },
  ],
  edges: [
    { id: "e1", from: { nodeId: "start", pinKey: "next" }, to: { nodeId: "const-flag-name", pinKey: "in" } },
    { id: "e2", from: { nodeId: "const-flag-name", pinKey: "out" }, to: { nodeId: "const-flag-value", pinKey: "in" } },
    { id: "e3", from: { nodeId: "const-flag-value", pinKey: "out" }, to: { nodeId: "set-flag", pinKey: "in" } },
    { id: "e4", from: { nodeId: "set-flag", pinKey: "out" }, to: { nodeId: "const-intro", pinKey: "in" } },
    { id: "e5", from: { nodeId: "const-intro", pinKey: "out" }, to: { nodeId: "show-intro", pinKey: "in" } },
    { id: "e6", from: { nodeId: "show-intro", pinKey: "out" }, to: { nodeId: "const-flag-name-read", pinKey: "in" } },
    { id: "e7", from: { nodeId: "const-flag-name-read", pinKey: "out" }, to: { nodeId: "get-flag", pinKey: "in" } },
    { id: "e8", from: { nodeId: "get-flag", pinKey: "out" }, to: { nodeId: "const-flag-true", pinKey: "in" } },
    { id: "e9", from: { nodeId: "const-flag-true", pinKey: "out" }, to: { nodeId: "equals-flag", pinKey: "in" } },
    { id: "e10", from: { nodeId: "equals-flag", pinKey: "out" }, to: { nodeId: "if-flag", pinKey: "in" } },
    { id: "e11", from: { nodeId: "if-flag", pinKey: "then" }, to: { nodeId: "const-prompt", pinKey: "in" } },
    { id: "e12", from: { nodeId: "if-flag", pinKey: "else" }, to: { nodeId: "const-alt", pinKey: "in" } },
    { id: "e13", from: { nodeId: "const-alt", pinKey: "out" }, to: { nodeId: "show-alt", pinKey: "in" } },
    { id: "e14", from: { nodeId: "show-alt", pinKey: "out" }, to: { nodeId: "end-alt", pinKey: "in" } },
    { id: "e15", from: { nodeId: "const-prompt", pinKey: "out" }, to: { nodeId: "wait-choice", pinKey: "in" } },
    { id: "e16", from: { nodeId: "wait-choice", pinKey: "choiceA" }, to: { nodeId: "const-delay", pinKey: "in" } },
    { id: "e17", from: { nodeId: "const-delay", pinKey: "out" }, to: { nodeId: "delay", pinKey: "in" } },
    { id: "e18", from: { nodeId: "delay", pinKey: "out" }, to: { nodeId: "subgraph", pinKey: "in" } },
    { id: "e19", from: { nodeId: "subgraph", pinKey: "out" }, to: { nodeId: "end", pinKey: "in" } },
    { id: "e20", from: { nodeId: "wait-choice", pinKey: "choiceB" }, to: { nodeId: "const-denom-name", pinKey: "in" } },
    { id: "e21", from: { nodeId: "const-denom-name", pinKey: "out" }, to: { nodeId: "const-denom-zero", pinKey: "in" } },
    { id: "e22", from: { nodeId: "const-denom-zero", pinKey: "out" }, to: { nodeId: "set-denom", pinKey: "in" } },
    { id: "e23", from: { nodeId: "set-denom", pinKey: "out" }, to: { nodeId: "const-denom-name-read", pinKey: "in" } },
    { id: "e24", from: { nodeId: "const-denom-name-read", pinKey: "out" }, to: { nodeId: "get-denom", pinKey: "in" } },
    { id: "e25", from: { nodeId: "get-denom", pinKey: "out" }, to: { nodeId: "to-number", pinKey: "in" } },
    { id: "e26", from: { nodeId: "to-number", pinKey: "out" }, to: { nodeId: "const-dividend", pinKey: "in" } },
    { id: "e27", from: { nodeId: "const-dividend", pinKey: "out" }, to: { nodeId: "divide", pinKey: "in" } },
    { id: "e28", from: { nodeId: "divide", pinKey: "onError" }, to: { nodeId: "const-error", pinKey: "in" } },
    { id: "e29", from: { nodeId: "const-error", pinKey: "out" }, to: { nodeId: "show-error", pinKey: "in" } },
    { id: "e30", from: { nodeId: "show-error", pinKey: "out" }, to: { nodeId: "end-error", pinKey: "in" } },

    { id: "d1", from: { nodeId: "const-flag-name", pinKey: "value" }, to: { nodeId: "set-flag", pinKey: "name" } },
    { id: "d2", from: { nodeId: "const-flag-value", pinKey: "value" }, to: { nodeId: "set-flag", pinKey: "value" } },
    { id: "d3", from: { nodeId: "const-intro", pinKey: "value" }, to: { nodeId: "show-intro", pinKey: "text" } },
    { id: "d4", from: { nodeId: "const-flag-name-read", pinKey: "value" }, to: { nodeId: "get-flag", pinKey: "name" } },
    { id: "d5", from: { nodeId: "get-flag", pinKey: "value" }, to: { nodeId: "equals-flag", pinKey: "a" } },
    { id: "d6", from: { nodeId: "const-flag-true", pinKey: "value" }, to: { nodeId: "equals-flag", pinKey: "b" } },
    { id: "d7", from: { nodeId: "equals-flag", pinKey: "isEqual" }, to: { nodeId: "if-flag", pinKey: "condition" } },
    { id: "d8", from: { nodeId: "const-prompt", pinKey: "value" }, to: { nodeId: "wait-choice", pinKey: "prompt" } },
    { id: "d9", from: { nodeId: "const-delay", pinKey: "value" }, to: { nodeId: "delay", pinKey: "ms" } },
    { id: "d10", from: { nodeId: "const-denom-name", pinKey: "value" }, to: { nodeId: "set-denom", pinKey: "name" } },
    { id: "d11", from: { nodeId: "const-denom-zero", pinKey: "value" }, to: { nodeId: "set-denom", pinKey: "value" } },
    { id: "d12", from: { nodeId: "const-denom-name-read", pinKey: "value" }, to: { nodeId: "get-denom", pinKey: "name" } },
    { id: "d13", from: { nodeId: "const-dividend", pinKey: "value" }, to: { nodeId: "divide", pinKey: "a" } },
    { id: "d14", from: { nodeId: "get-denom", pinKey: "value" }, to: { nodeId: "to-number", pinKey: "value" } },
    { id: "d15", from: { nodeId: "to-number", pinKey: "number" }, to: { nodeId: "divide", pinKey: "b" } },
    { id: "d16", from: { nodeId: "const-error", pinKey: "value" }, to: { nodeId: "show-error", pinKey: "text" } },
    { id: "d17", from: { nodeId: "const-alt", pinKey: "value" }, to: { nodeId: "show-alt", pinKey: "text" } }
  ],
  subgraphs: {
    subflow: {
      id: "subflow",
      version: 1,
      entryNodeId: "sub-start",
      nodes: [
        { id: "sub-start", type: "Start", version: 1, props: {}, pos: { x: 0, y: 0 } },
        { id: "sub-text", type: "ConstString", version: 1, props: { value: "Subgraph executed successfully." }, pos: { x: 200, y: 0 } },
        { id: "sub-show", type: "ShowText", version: 2, props: { title: "Subgraph" }, pos: { x: 400, y: 0 } },
        { id: "sub-end", type: "End", version: 1, props: {}, pos: { x: 600, y: 0 } },
      ],
      edges: [
        { id: "s1", from: { nodeId: "sub-start", pinKey: "next" }, to: { nodeId: "sub-text", pinKey: "in" } },
        { id: "s2", from: { nodeId: "sub-text", pinKey: "out" }, to: { nodeId: "sub-show", pinKey: "in" } },
        { id: "s3", from: { nodeId: "sub-show", pinKey: "out" }, to: { nodeId: "sub-end", pinKey: "in" } },
        { id: "s4", from: { nodeId: "sub-text", pinKey: "value" }, to: { nodeId: "sub-show", pinKey: "text" } },
      ],
    },
  },
};
